version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: ticket_booking_db
    environment:
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: topsecretpassword123
      POSTGRES_DB: ticket_booking
    ports:
      - "5433:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    restart: unless-stopped

volumes:
  postgres_data: